import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Parkeer",
  description: "Generated by create next app",
};

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.className}  antialiased`}>{children}</body>
    </html>
  );
}
